"""
Automated Threat Intelligence & Rule Generator (YARA, Snort/Suricata, STIX 2.1)
Cyber Squad TUI - SIH Problem Statement #26106
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List


def generate_yara_rule(evidence: Dict[str, Any], threat_data: Dict[str, Any]) -> str:
    """
    Generates a valid YARA rule based on extracted email artifacts, sender, attachments, and URLs.
    """
    sha256 = evidence.get("sha256", "0" * 64)
    subject = evidence.get("meta", {}).get("subject", "").replace('"', '\\"')
    sender = evidence.get("meta", {}).get("from", "").replace('"', '\\"')
    attachments = evidence.get("attachments", [])
    urls = threat_data.get("url_analysis", [])

    rule_name = f"Email_Threat_Hunting_{sha256[:12]}"
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    string_lines: List[str] = []
    str_idx = 1

    # Subject match
    if subject:
        clean_subj = re.sub(r'[\r\n]', ' ', subject).strip()[:80]
        string_lines.append(f'        $s{str_idx} = "{clean_subj}" ascii wide nocase')
        str_idx += 1

    # Sender match
    if sender:
        clean_sender = re.sub(r'[\r\n]', ' ', sender).strip()[:60]
        string_lines.append(f'        $s{str_idx} = "{clean_sender}" ascii wide nocase')
        str_idx += 1

    # High risk URLs
    for u in urls[:3]:
        domain = u.get("domain", "")
        if domain:
            string_lines.append(f'        $url{str_idx} = "{domain}" ascii wide nocase')
            str_idx += 1

    # Attachment hashes or filenames
    for att in attachments[:3]:
        att_name = att.get("filename", "")
        if att_name:
            string_lines.append(f'        $att{str_idx} = "{att_name}" ascii wide nocase')
            str_idx += 1

    strings_block = "\n".join(string_lines) if string_lines else '        $default = "Subject:" ascii wide'

    yara_text = f"""/*
    YARA Threat Hunting Rule Auto-Generated by Cyber Squad TUI
    Target SHA-256 : {sha256}
    Generated Date : {now_str}
    Verdict        : {threat_data.get('verdict', 'SUSPICIOUS')}
*/

rule {rule_name}
{{
    meta:
        author = "Cyber Squad Incident Response Engine (SIH #26106)"
        description = "Automated YARA rule targeting malicious email indicators and IOCs"
        reference_sha256 = "{sha256}"
        date = "{now_str}"
        severity = "{threat_data.get('risk_score', 0)}"

    strings:
{strings_block}

    condition:
        2 of them or any of ($att*)
}}
"""
    return yara_text.strip()


def generate_snort_rule(evidence: Dict[str, Any], threat_data: Dict[str, Any]) -> str:
    """
    Generates Snort / Suricata IDS network signature rules for perimeter defense.
    """
    sha256 = evidence.get("sha256", "0" * 64)
    subject = evidence.get("meta", {}).get("subject", "").replace('"', '')
    clean_subj = re.sub(r'[\r\n;:]', ' ', subject).strip()[:60]
    urls = threat_data.get("url_analysis", [])
    
    rules: List[str] = []
    sid_start = 9000001

    # SMTP Subject alert
    if clean_subj:
        rule_smtp = (
            f'alert tcp any any -> any [25,587] (msg:"CYBERSQUAD [MALWARE/PHISH] Suspicious Email Subject Observed ({clean_subj[:30]})"; '
            f'flow:to_server,established; content:"Subject: "; nocase; content:"{clean_subj}"; nocase; '
            f'classtype:trojan-activity; sid:{sid_start}; rev:1; metadata:created_at {datetime.now(timezone.utc).strftime("%Y_%m_%d")};)'
        )
        rules.append(rule_smtp)
        sid_start += 1

    # HTTP / DNS outbound alerts for malicious URLs
    for u in urls[:2]:
        domain = u.get("domain", "")
        if domain:
            rule_http = (
                f'alert tcp any any -> any [80,443] (msg:"CYBERSQUAD [IOC] Outbound Phishing Domain Connection to {domain}"; '
                f'flow:to_server,established; content:"{domain}"; http_header; '
                f'classtype:bad-unknown; sid:{sid_start}; rev:1;)'
            )
            rules.append(rule_http)
            sid_start += 1

    return "\n\n".join(rules) if rules else f'# No high-risk network indicators extracted for {sha256[:12]}'


def generate_stix_bundle(evidence: Dict[str, Any], threat_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generates a STIX 2.1 Threat Intelligence JSON object.
    """
    now_iso = datetime.now(timezone.utc).isoformat()
    sha256 = evidence.get("sha256", "")
    subject = evidence.get("meta", {}).get("subject", "")
    sender = evidence.get("meta", {}).get("from", "")

    indicator_id = f"indicator--{sha256[:8]}-0000-4000-8000-{sha256[8:20]}"
    pattern_parts = [f"[file:hashes.'SHA-256' = '{sha256}']"]
    if sender:
        pattern_parts.append(f"[email-message:from_ref.value = '{sender}']")

    return {
        "type": "bundle",
        "id": f"bundle--{sha256[:8]}-sih2026-threat-bundle",
        "spec_version": "2.1",
        "objects": [
            {
                "type": "indicator",
                "spec_version": "2.1",
                "id": indicator_id,
                "created": now_iso,
                "modified": now_iso,
                "name": f"Phishing/Malware Email IOC: {subject[:50]}",
                "description": f"Extracted threat indicators with risk score {threat_data.get('risk_score', 0)}/100",
                "indicator_types": ["malicious-activity", "phishing"],
                "pattern": " OR ".join(pattern_parts),
                "pattern_type": "stix",
                "valid_from": now_iso,
            }
        ]
    }


def export_threat_rules(
    evidence: Dict[str, Any],
    threat_data: Dict[str, Any],
    output_dir: str | Path = "./forensic_exports",
) -> Dict[str, str]:
    """
    Exports YARA, Snort, and STIX rules to disk.
    """
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    sha256 = evidence.get("sha256", "evidence")[:12]
    
    yara_text = generate_yara_rule(evidence, threat_data)
    snort_text = generate_snort_rule(evidence, threat_data)
    stix_json = generate_stix_bundle(evidence, threat_data)
    
    yara_file = out_path / f"threat_rule_{sha256}.yar"
    snort_file = out_path / f"snort_rule_{sha256}.rules"
    stix_file = out_path / f"stix_bundle_{sha256}.json"
    
    yara_file.write_text(yara_text, encoding="utf-8")
    snort_file.write_text(snort_text, encoding="utf-8")
    stix_file.write_text(json.dumps(stix_json, indent=2), encoding="utf-8")
    
    return {
        "yara": str(yara_file.resolve()),
        "snort": str(snort_file.resolve()),
        "stix": str(stix_file.resolve()),
    }
